// Generated by https://quicktype.io

class Genres {
  List<Genre> items = List();

  Genres();

  Genres.fromJsonList(List<dynamic> jsonList) {
    if (jsonList == null) return;
    items.addAll(jsonList.map((genre) => Genre.fromJsonMap(genre)).toList());
  }
}

class Genre {
  int id;
  String name;

  Genre({
    this.id,
    this.name,
  });

  Genre.fromJsonMap(Map<String, dynamic> json) {
    id = json["id"];
    name = json["name"];
  }
}
